version: "3"

services:
  webapp:
    build: ./webapp
    image: ml-in-prod-webapp
    container_name: webapp
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
